"""
init_enforcer.py — Global Gradle init.d version enforcement manager.

Generates and installs ~/.gradle/init.d/align-cache-versions.gradle.kts
to enforce unified dependency resolutions across all builds on the machine.
"""

from pathlib import Path
from project_scanner import get_or_create_baseline

INIT_SCRIPT_PATH = Path.home() / ".gradle" / "init.d" / "align-cache-versions.gradle.kts"

def is_enforcer_enabled() -> bool:
    """Check if the global alignment init script is currently active."""
    return INIT_SCRIPT_PATH.exists()

def enable_enforcer(baseline: dict = None) -> dict:
    """Generate and write the init script based on the machine baseline."""
    if baseline is None:
        baseline = get_or_create_baseline()

    versions = baseline.get("versions", {})
    INIT_SCRIPT_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Generate resolutionStrategy.force rules
    force_rules = []
    # Map common version catalog keys to actual Maven coordinates
    mapping = {
        "kotlin": ["org.jetbrains.kotlin:kotlin-stdlib", "org.jetbrains.kotlin:kotlin-reflect"],
        "ktor": ["io.ktor:ktor-client-core", "io.ktor:ktor-client-cio"],
        "koin": ["io.insert-koin:koin-core"],
        "coroutines": ["org.jetbrains.kotlinx:kotlinx-coroutines-core"],
        "serialization": ["org.jetbrains.kotlinx:kotlinx-serialization-json"],
        "coil": ["io.coil-kt:coil", "io.coil-kt.coil3:coil"],
    }

    for k, v in versions.items():
        if k in mapping:
            for coord in mapping[k]:
                force_rules.append(f'            force("{coord}:{v}")')

    content = f"""// Auto-generated by Gradle Cache Manager
// Enforces machine-wide unified version resolution to save disk storage and share caches.
allprojects {{
    if (name == "gradle-version-guard" || rootProject.name == "gradle-version-guard") {{
        return@allprojects
    }}
    configurations.all {{
        resolutionStrategy {{
{chr(10).join(force_rules) if force_rules else "            // Baseline active"}
        }}
    }}
}}
"""
    INIT_SCRIPT_PATH.write_text(content)
    return {"enabled": True, "path": str(INIT_SCRIPT_PATH)}

def disable_enforcer() -> dict:
    """Remove the init script if active."""
    if INIT_SCRIPT_PATH.exists():
        INIT_SCRIPT_PATH.unlink()
    return {"enabled": False}
